### ISSUE TITLE
Feature Request: Custom sort order

### ISSUE THREAD

**Issue by AdvanceWM** [pixelant/pxa_product_manager#100]
There are times, especially when an alphabetical list of products includes numbers in their names, when a custom sort order would be useful. I could fudge it by using Date order and adjusting the dates manually. Now when we have a list like:
* 6 kilo weight
* 8 kilo weight
* 12 kilo weight
the 12 kilo weight is listed first alphabetically.

It would be nice to be able to control that sort order.

Thank you

**Comment by pixelmatseriks** [comment]
Hi Tony,

There is a custom_sorting in product manager, but the "score" is calculated by assigning "points" in typoscript configuration to categories and if the product is new, so probably isn't the solution for you.

But if you can sort products by another property, it is possible to add it as an option in the plugin options: "Product ordering"  -> "Sort by"

In following example I add the SKU property as a sort by option:

Page TS
```
# Add new item to dropdown in plugin settings flexform of Product Manager Plugin
TCEFORM.tt_content.pi_flexform.pxaproductmanager_pi1.productOrderings.settings\.orderProductBy.addItems.sku = By SKU

```
Setup TS
```
# Add sku to orderByAllowed
plugin.tx_pxaproductmanager.settings.orderByAllowed = name,tstamp,crdate,categories,categories.sorting,custom_sorting,sorting,sku
```

**Comment by AdvanceWM** [comment]
That's a helpful hint, Mats.

Thank you

**Comment by AdvanceWM** [comment]
Is there a similar technique that could apply to category sorting? I don't see any settings in the typoscript configuration for that.

**Comment by pixelmatseriks** [comment]
It is possible to select the order of categories in plugin options tab "Category ordering" in plugin mode "List view (Possible navigation)". By default it is possible to order by sorting and title, but it is possible to add for other fields.

Example to sort by uid field:

Page TS
```
# Add new item to dropdown in plugin settings flexform of Product Manager Plugin
TCEFORM.tt_content.pi_flexform.pxaproductmanager_pi1.categoriesOrderings.settings\.orderCategoriesBy.addItems.uid = By Id

```

**Comment by AdvanceWM** [comment]
Many thanks, Mats

**Comment by AdvanceWM** [comment]
As a workaround for category sorting, I used the one of the Product Manager fields added to sys_category that I did not see being used at this time -- pxapm_tax_rate. 

Setting in PageTS:
# Add new item to dropdown in plugin settings flexform of Product Manager Plugin
TCEFORM.tt_content.pi_flexform.pxaproductmanager_pi1.categoriesOrderings.settings\.orderCategoriesBy.addItems.pxapm_tax_rate = By Tax Rate

Then I could use MySQL Workbench or phpMyAdmin to manually set a tax rate for Parent Categories and Child Categories to achieve the desired sorting.

This is strictly a workaround, and I would like to see a way to sort Categories that is more accessible to the normal website admin.
