### ISSUE TITLE
Categories in Subfolders and Relations between Products

### ISSUE THREAD

**Issue by elgato42** [pixelant/pxa_product_manager#102]
I have 2 problems and i’m not sure if it is an error in the extension or intended behavior. I use Typo3 9.5.4 with PHP 7.2 and the latest pxa_product_manager.

Nr. 1
I have a main folder **Productstorage** and inside this Folder i have sub folder **Cars** and **Boats**. I created Categories inside **Productstorage** like this, main categorie **Cars** and sub categorie **big, medium and little**, same with the **Boats**.

If I create a product inside of **Productstorage** everything is fine, I can chose a categorie and the product is displayed in the frontend. But if i create the product in one of the sub folders **Cars or Boats** i can’t chose a categorie because they are not there, it looks like i dont have any categories.

Did I something wrong or is it the intended behavior and everything should be in one folder?

Nr. 2

Its about the relations between products, lets say I have **Product 1** and **Product 2**. When I make **Produkt 1** related to **Product 2**, **Product 2** is not automatically related to **Product 1**, I need to go to **Product 2** and chose **Product 1** as related.

In my Opinion it would make more sense(and in most Shops it is like this) when **Product 1** is chosen to be related to **Product 2** then **Product 2** should be automatically related to **Product 1** without an extra step.

English is not my strong side, I hope it is clear what I tried to describe, if something is not I gladly provide more info.

**Comment by anjeylink** [comment]
Hi.
1. In extension settings set "dontCheckPidForSysCategory" to "Yes". In TYPO3 9 there is new module "Settings", where you can set extension settings. 

2. Good idea, thx for feedback

**Comment by elgato42** [comment]
Hi, thank you very much, that solved the Problem.
