### ISSUE TITLE
Remove SKU from URL

### ISSUE THREAD

**Issue by AdvanceWM** [pixelant/pxa_product_manager#111]
I see in the configuration for realURL mention of "$enableSkuInUrl" in Classes/RealUrl/realurl.php.

Where can I set that to 0?

**Comment by pixelmatseriks** [comment]
You can set it in Extension Manager configuration for Product Manager

**Comment by AdvanceWM** [comment]
Ahh, I should have looked there. ;)

**Comment by AdvanceWM** [comment]
I set basic.includeSkuInRealurlConfiguration  to "no" in the Extensions configuration, but the SKU persists in the URL (8.11.8 Products Manager). Clearing caches done.

**Comment by anjeylink** [comment]
You need also to clean realurl unique alias and URL data cache tables

**Comment by AdvanceWM** [comment]
Thank you, Andriy. That took care of it.
