### ISSUE TITLE
Can't create first product in category using Products Manager 

### ISSUE THREAD

**Issue by Aero91** [pixelant/pxa_product_manager#112]
It is not possible to create a new product in a category using the Products Manager module if that category is empty. So the first product in each category has to be created in list view.

**Comment by nasiri** [comment]
This is not an enhancement, it is acutally a bug. You don't want editors to go inside of the List View. So if you can add a category as a editor but don't able to add the product itself, it shouldn't be considered an enhancement!

**Comment by MattiasNilsson** [comment]
The backend module is removed and List view is the way forward.
