### ISSUE TITLE
Discontinued products and Lazy List

### ISSUE THREAD

**Issue by Aero91** [pixelant/pxa_product_manager#114]
Discontinued products don't show up in Lazy Lists even if the list is configured to show them.

**Comment by anjeylink** [comment]
@Aero91 I can't reproduce this. Which version are you using?

**Comment by Aero91** [comment]
@anjeylink Version 9.6.4 and TYPO 8.7.24

**Comment by MattiasNilsson** [comment]
@Aero91 Is this issue still relevant?
