### ISSUE TITLE
Filtering with attributes - multilanguage

### ISSUE THREAD

**Issue by janadtheplanet** [pixelant/pxa_product_manager#137]
When adding a new product in the default language (0) everything works. 
Now when we translate a product, the field 'l10n_parent' of that (translated) product in the table 'tx_pxaproductmanager_domain_model_attributevalue' remains empty (or zero) afterwards. 

This seems to lead to a bug where the filters do not work when we try to use attributes for filtering in the second (translated) language. 

If we add the correct value (uid of the default-language record) for 'l10n_parent' into the table 'tx_pxaproductmanager_domain_model_attributevalue' manually the filtering works. 
If we do not add the value by hand filtering over attributes does not work...

**Comment by nasiri** [comment]
I have the same problem. A fix would be very helpful.

**Comment by MattiasNilsson** [comment]
Is this till an issue?
