### ISSUE TITLE
Assignment of subcategories (multilanguage)

### ISSUE THREAD

**Issue by m-strotmeier** [pixelant/pxa_product_manager#139]
My customer has a large product range with categories and subcategories. On the list page in page tree, we chose your Plugin with "List view (Possible navigation)". In the default language everything works fine: the page shows me all available subcategories first, then I can click into the subcategorie to show the related products. Plus I can see the subcategories in backend, tab "Sub-Categories" in the super category.
When we translate the products, the assignment of subcategories does not seem to work. Neither in frontend nor in backend tab "Sub-Categories", the sub categories are available (thus assigned as parent category of the subcategory dataset itself).

**Comment by m-schmitz** [comment]
To visualize, please see the attached screenshots
![subcategories-en](https://user-images.githubusercontent.com/9283637/63169060-20a59400-c036-11e9-9f94-387fa1788c14.PNG)
![subcategories-de](https://user-images.githubusercontent.com/9283637/63169061-20a59400-c036-11e9-98d7-2c66fc0465a6.PNG)

**Comment by MattiasNilsson** [comment]
Categories are not relevant anymore.
