### ISSUE TITLE
Language fallback for products

### ISSUE THREAD

**Issue by m-strotmeier** [pixelant/pxa_product_manager#140]
**I am currently using TYPO3 9.5.8 and pxa_product_manager 9.8.6.**

My customer has the requirement, that translated products should use fallback at least for attribute values (or for the whole product dataset with all subs). If a product is translated into 5 more languages, he wants to change the attribute values in the default language only (of course: only numeric values, not any values that need translation).

After hours of researching through your extension and the core, I could not figure out a way to do this. Is there a way ´? Or wouldn't this be a nice feature?

Best regards (your extension is awesome, I like working with it as it is so dynamic)!

**Comment by MattiasNilsson** [comment]
@m-strotmeier Is this still relevant for you?

**Comment by m-strotmeier** [comment]
@MattiasNilsson 
Thanks for asking, but from my side you can close the ticket for now. 
Keep up the good work and thx for the new version 10.x.x.

**Comment by MattiasNilsson** [comment]
@m-strotmeier Thanks for the nice feedback! We also have release a TYPO3 v11 compatible version today: https://github.com/pixelant/pxa_product_manager/releases/tag/v11.0.0
