### ISSUE TITLE
Solr Search Product Attributes are not getting indexed!

### ISSUE THREAD

**Issue by nasiri** [pixelant/pxa_product_manager#143]
Hello guys,

i used the typoscript files for the Solr Settings,

and i can't get the Attributes to be indexed. 

i removed the commenttags to allow following code to be used:

        attribute_name = USER
        attribute_name {
            userFunc = Pixelant\PxaProductManager\UserFunction\SolrIndexSingleAttributeValue->getSingleAttributeValue
            identifier = name
        }

Could you tell me if something is being forgotten from my side?

**Comment by anjeylink** [comment]
@nasiri Hi, you should specify type of custom solr fields. 
https://docs.typo3.org/typo3cms/extensions/solr/stable/Appendix/DynamicFieldTypes.html

 you field should have name something like "attribute_name_stringS"

**Comment by nasiri** [comment]
Thx. Perfect. Got it!
