### ISSUE TITLE
Discussion/Change: Attribute sets

### ISSUE THREAD

**Issue by jacobsenj** [pixelant/pxa_product_manager#149]
Hi,

I think attribute sets should not be bound to a category but instead directly to a product. If you bind attribute sets to categories, you are not able to have categories with different products. In medicine, for example, there are pills and ointments. Let's say we have a category "Pain" and now we have different types of products in this category that cannot have different attributes because the sets are tied to categories and not to products.

I started a branch which moves the attribute sets from categories to products here:
https://github.com/jacobsenj/pxa_product_manager/tree/feature/link-attribute-sets-to-products-insteadof-categories

What do you think about it?

Cheers
Jens

**Comment by jacobsenj** [comment]
Hello,

I'm still interested in your thoughts about this matter.

Cheers
Jens

**Comment by anjeylink** [comment]
@jacobsenj Hi. thx for you feedback. I think it can be configurable on extension level, but I'm not sure if this can be implemented in version 9.

**Comment by MattiasNilsson** [comment]
This will be a part of version 10 which we are working on. So will close this issue.
