### ISSUE TITLE
Single View Page ignored – Still using List View Page

### ISSUE THREAD

**Issue by KodiakWeb** [pixelant/pxa_product_manager#150]
When I'm setting up the List-View-Plugin and defining the product page, it still uses the List-View-Page to show the selected product in single view.

I've already set up the Single-View-Plugin on the product page.

I want to use an own page for the Single-View, because else the content above the List-View-Plugin is also shown on the Single-View-Page.

I'm using:
Typo3 9.5.8
Product Manager 9.9.0

**Comment by anjeylink** [comment]
@KodiakWeb was fixed
