### ISSUE TITLE
Lazy List View – No Single View

### ISSUE THREAD

**Issue by KodiakWeb** [pixelant/pxa_product_manager#151]
When I'm setting up the Lazy-List-View (because I want to use the filters), the products can't be shown in the Single View.

It just reloads the Lazy-List-Page with all products unfiltered again.

In the URL the showAction seems to be called, but nothing happens.
(…?tx_pxaproductmanager_pi1%5Baction%5D=show&tx_pxaproductmanager_pi1%5Bcategory_0%5D=1&tx_pxaproductmanager_pi1%5Bcontroller%5D=Product&tx_pxaproductmanager_pi1%5Bproduct%5D=1&cHash=b3ffd2365cbb1cd33a29f5e602dbbe42#pm%3A%7B"limit"%3A0%7D)

There are no errors in the browser console.

I'm using:
Typo3 9.5.8
Product Manager 9.9.0

**Comment by nasiri** [comment]
I had the same Problem. I put the Typo3 Site ID of the Single Page View in the Template of the Extension. Or maybe you haven't set the default single page id in the constants?

**Comment by anjeylink** [comment]
@KodiakWeb lazy loading view doesn't support single view. you should be separate page for single view. It might be fixed in future

**Comment by anjeylink** [comment]
@KodiakWeb @nasiri you can update extension now. it was fixed. Don't forget to choose lazy loading in flexform settings again
