### ISSUE TITLE
Question: RouteEnhancers without Category in the Path

### ISSUE THREAD

**Issue by bh-teufels** [pixelant/pxa_product_manager#152]
Hello,

is it possible to display the "One Level" routes without the argument `category_0`?
if i leave out the `category_title_0` in the routePath it appears (with cHash) as parameter to the url.

How it is now: `https://mydomain/products/product-title?tx_pxaproductmanager_pi1%5Bcategory_0%5D=4&cHash=1s387d864drtac359cb147d1c6ea896`
what i want: `https://mydomain/products/product-title`

Thank you

**Comment by anjeylink** [comment]
@bh-teufels use constant and remove "category_title_0' from routes

`plugin.tx_pxaproductmanager.settings.excludeCategoriesFromUrl = 1`

**Comment by bh-teufels** [comment]
Thank you very much.
i was so focused on route Enhancers that I overlooked that.

**Comment by bh-teufels** [comment]
i set `plugin.tx_pxaproductmanager.settings.excludeCategoriesFromUrl = 1` in Constants and Setup but the category is still in the URL

`tx_pxaproductmanager_pi1%5Bcategory_0%5D=4&cHash=1s387d864drtac359cb147d1c6ea896`

**Comment by bh-teufels** [comment]
@anjeylink do you have any tips why it still hat the category in the url?

**Comment by anjeylink** [comment]
@bh-teufels there was a bug. you also need to update your routes like here
https://github.com/pixelant/pxa_product_manager/pull/153/files#diff-217954e3b5827d3a78fd8f2ad533f3f6

**Comment by bh-teufels** [comment]
I updated to Version 9.9.1.
But i use GroupedList. 
Do i have to replace 
`<ppm:link.link pageUid="{settings.pagePid}" category="{category}" product="{product}">` 
with 
`<ppm:link.link pageUid="{settings.pagePid}" category="{category}" product="{product}" excludeCategories="{settings.excludeCategoriesFromUrl}">` 
here too

**Comment by bh-teufels** [comment]
adding `excludeCategories="{settings.excludeCategoriesFromUrl}"` to GroupedList, Related, ... works for me.

Thank you
