### ISSUE TITLE
Update for TYPO3 10.4.x

### ISSUE THREAD

**Issue by schorsch8878** [pixelant/pxa_product_manager#197]
Hello, are there any plans for a update for TYPO3 10 ??

Many Thanks

George

**Comment by erredeco** [comment]
I would be interested, too

**Comment by bavarianbytes** [comment]
Me too!

**Comment by m-strotmeier** [comment]
Hey, we are also using this extension and are wondering how it proceeds. Are there any plans for compatibility to 10LTS and 11LTS?

**Comment by MattiasNilsson** [comment]
Hi all you can the see the answer in this task: https://github.com/pixelant/pxa_product_manager/issues/313

**Comment by MattiasNilsson** [comment]
For all your information we have now released TYPO3 v10 compatible version: https://github.com/pixelant/pxa_product_manager/releases/tag/v10.0.0

@m-strotmeier @schorsch8878 @erredeco @bavarianbytes
