### ISSUE TITLE
Create UML diagram

### ISSUE THREAD

**Issue by mabolek** [pixelant/pxa_product_manager#201]
Illustrate the object and data structure of the extension.

- [x] Create diagrams
- [x] Add to documentation

**Comment by mabolek** [comment]
Diagrams created. Next: Add to documentation.

![pxa_product_manager-classes-only-25-nov-2020](https://user-images.githubusercontent.com/8200271/100248291-9a1b7a00-2f3b-11eb-9f20-54cfaf023356.png)
![pxa_product_manager-classes-25-nov-2020](https://user-images.githubusercontent.com/8200271/100248297-9c7dd400-2f3b-11eb-9844-c30c1e80689a.png)

**Comment by MattiasNilsson** [comment]
@mabolek I assume this can be closed as it is resolved?
