### ISSUE TITLE
Does list view support paging?

### ISSUE THREAD

**Issue by bavarianbytes** [pixelant/pxa_product_manager#229]
Can't find anything.

**Comment by pixelmatseriks** [comment]
No, current version of product managers list view doesn't have any pagination.

**Comment by MattiasNilsson** [comment]
@bavarianbytes Is this feature still relevant for you? As we are mainly using lazy loading now.

**Comment by MattiasNilsson** [comment]
@bavarianbytes I am closing this and will be referring to this task instead regarding the pagination. #282
