### ISSUE TITLE
Error when you flush cache

### ISSUE THREAD

**Issue by VladVilya** [pixelant/pxa_product_manager#277]
On the current branch v10_alpha, after flush cache error appears:

Cannot autowire service "Pixelant\PxaProductManager\Domain\Repository\ProductRepository": argument "$demandService" of method "Pixelant\PxaProductManager\Domain\Repository\AbstractDemandRepository::injectDemandService()" references class "Pixelant\Demander\Service\DemandService" but no such service exists.

**Comment by pixelmatseriks** [comment]
can you try and update the "demander" extension and see if it helps

**Comment by MattiasNilsson** [comment]
@VladVilya Did the fix Mats mentioned solve this issue?
