### ISSUE TITLE
Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchAllAssociative()

### ISSUE THREAD

**Issue by slymbo** [pixelant/pxa_product_manager#285]
**pxa_product_manager_10 (v10_alpha) branch**

https://github.com/pixelant/pxa_product_manager/tree/v10_alpha

The problem the current versions of Typo3 **"10.x"** didn't support the new version of **doctrine**.

It's better if you replace  the current function `fetchAllAssociative()` with the old one `fetchAll()` .

This is the list of function using `fetchAllAssociative()` 

```
protected function fetchDuplicateAttributeValues()
public static function findAttributeOptions(int $attributeId, string $selectFields = '*')
protected function fetchDuplicateAttributeValues()
protected function fetchAttributeValueData(int $attribute, int $product)
protected function fetchMissingChildRelations()
```

**Comment by pixelmatseriks** [comment]
Hi, thanks for taking the time to report this issue.
What version of doctrine/dbal do you have?
If I change to fetchAll(), I get a deprecation notice "@deprecated Use fetchAllNumeric(), fetchAllAssociative() or fetchFirstColumn() instead."

**Comment by slymbo** [comment]
Hi, 
Version 2.10 it's the default version of Typo3 10.4.x

**Comment by slymbo** [comment]
@pixelmatseriks 
In this link 
https://www.doctrine-project.org/2020/11/17/dbal-3.0.0.html

Look at this part please **Upgrading to DBAL 3 from 2**,
They support just from 2.12, by this way you can make condition if the version of doctrine less than that it will use `fetchAll()`.
