### ISSUE TITLE
[FEATURE] TYPO3 11 compatibility

### ISSUE THREAD

**Issue by bavarianbytes** [pixelant/pxa_product_manager#313]
Is a compatibility to version 11 planned?

**Comment by mabolek** [comment]
Yes, planned, but not currently scheduled. 

Feel free to contribute or sponsoring features. 

The most recent work is happening in this branch: https://github.com/pixelant/pxa_product_manager/tree/v10_alpha

We also accept donations: https://www.paypal.com/donate/?hosted_button_id=B7YZKNCHTYHRW

**Comment by MattiasNilsson** [comment]
Just for you information we have releases a TYPO3 v10 compatible version: https://github.com/pixelant/pxa_product_manager/releases/tag/v10.0.0

@bavarianbytes

**Comment by MattiasNilsson** [comment]
@bavarianbytes We just released a v11 that supports TYPO3 v11 and PHP 8.

https://github.com/pixelant/pxa_product_manager/releases/tag/v11.0.0
