### ISSUE TITLE
[FEATURE] Complete and replace external google docs-documentation with rendered REST-documentation

### ISSUE THREAD

**Issue by pxamike** [pixelant/pxa_product_manager#336]
The google docs documentation is somewhat out of date, is not public available and updating it when new features are added is often forgotten.

Complete the REST-documentation (which is part of the extension anyway) with anything that is missing from the google docs and publish it to typo3.org extension documentation, so it's public available and easy to keep up to date.

**Comment by MattiasNilsson** [comment]
@pxamike There is a PR for this up, maybe you can take a look at it? https://github.com/pixelant/pxa_product_manager/pull/334

**Comment by pxamike** [comment]
@MattiasNilsson ah great!
