### ISSUE TITLE
Route Enhancer not working with v11 [BUG]

### ISSUE THREAD

**Issue by bh-teufels** [pixelant/pxa_product_manager#384]
The Route Enhancer does not working anymore on
Typo3 11.5.13
pxa_product_manager 11.0.6

i used the code provided by pxa_product_manager/Configuration/RoutingExample/RouteEnhancers.yaml

does anybody have a working example of the route enhancer on Typo3 11?

**Comment by bh-teufels** [comment]
i see that the PluginName has changed from Pi1 (for list, show) to different Plugins for each action.
how should the route enhancers look when  i want to achieve the following:

**Detail:**

_URL looks like:_ 
http://my-domain.com/product/?tx_pxaproductmanager_productshow%5Baction%5D=show&tx_pxaproductmanager_productshow%5Bcontroller%5D=ProductShow&tx_pxaproductmanager_productshow%5BextensionName%5D=PxaProductManager&tx_pxaproductmanager_productshow%5BpluginName%5D=ProductShow&tx_pxaproductmanager_productshow%5Bproduct%5D=1&cHash=a97070f5e9e09d7e944b615d2344b679

_URL should look like:_ 
http://my-domain.com/subfolder/<product_title>

**Listing:** 
i use 1 Filter (Radio, Category, OR) and
1 Filter (Checkbox, Attribute Mutliselect, AND) 
and want to have also speaking URLs for the Filter

_URL looks like:_ 

- Category Filter: http://my-domain.com/sortiment/#filterConjunction=and&filters={%221%22:{%22conjunction%22:%22or%22,%22attribute%22:0,%22type%22:1,%22value%22:[24]}}&hideFilterOptionsNoResult=0&limit=5&offSet=0&orderBy=name&orderDirection=asc&pageTreeStartingPoint=9&storagePid=[11]

- Attribute Filter: http://my-domain.com/sortiment/#filterConjunction=and&filters={"3":{"conjunction":"or","attribute":12,"type":2,"value":[5]}}&hideFilterOptionsNoResult=0&limit=5&offSet=0&orderBy=name&orderDirection=asc&pageTreeStartingPoint=9&storagePid=[11]

- Combined Filter: http://my-domain.com/sortiment/#filterConjunction=and&filters={%221%22:{%22conjunction%22:%22or%22,%22attribute%22:0,%22type%22:1,%22value%22:[24]},%223%22:{%22conjunction%22:%22or%22,%22attribute%22:12,%22type%22:2,%22value%22:[5]}}&hideFilterOptionsNoResult=0&limit=5&offSet=0&orderBy=name&orderDirection=asc&pageTreeStartingPoint=9&storagePid=[11]

**Comment by bh-teufels** [comment]
with the following code for route enhancer i get the product name in the url but still having 
`/?tx_pxaproductmanager_productshow%5BextensionName%5D=PxaProductManager&tx_pxaproductmanager_productshow%5BpluginName%5D=ProductShow&cHash=853401fd9a159e75dc3afb7399c3dd62` in the url

`ProductShow:
    type: Extbase
    limitToPages: [8]
    extension: PxaProductManager
    plugin: ProductShow
    routes:
      -
        routePath: '/{product_title}'
        _controller: 'ProductShow::show'
        _arguments:
          product_title: product
    defaultController: 'ProductList::show'
    aspects:
      product_title:
        type: PersistedAliasMapper
        tableName: tx_pxaproductmanager_domain_model_product
        routeFieldName: slug`

**Comment by MattiasNilsson** [comment]
@bh-teufels We recommend that you use the plugin called ProductRender instead. This is due to the fact that it now uses pages instead of sys_categories and also have full support for proper routes out of the box.

**Comment by MattiasNilsson** [comment]
@bh-teufels Good to hear that is works!

**Comment by bh-teufels** [comment]
the topic "Speaking URL for Listing" is still present. 
is it possible to have route enhancer for the List filter?

**Comment by MattiasNilsson** [comment]
@bh-teufels Not at the moment, but it may come in some future update. As said before any PR is welcome!

**Comment by nasiri** [comment]
Hello dear @MattiasNilsson ,

i can confirm, that i have the same problem regarding the routeenhancingexample.

I am using the productrenderer, but the detail view is not using a rewritten URL. 
Its still just added to the existing url like: domain.xxx/products/groupname?tx_pxaproductmanager_productrender%5Baction%5D=init&tx_pxaproductmanager_productrender%5Bcontroller%5D=ProductRender&tx_pxaproductmanager_productrender%5Bproduct%5D=2&cHash=eb8b1b60db7a831ec389bc1b9eeb61a3
