### ISSUE TITLE
[BUG] Sorting "Product Renderer" List not working 

### ISSUE THREAD

**Issue by bh-teufels** [pixelant/pxa_product_manager#386]
**Describe the bug**
The Sorting of Plugin "Product Renderer" in List-View is not working.
Either the Setting in the plugin nor if the sorting is changed in the dropdown

` <sorting :options="{orderBy}" :settings="{settingsJson}"></sorting>`

if i change the sorting in the dropdown the url changes "correctly"
`orderBy=name&orderDirection=asc`

if i select the ordering i set in the plugin the sorting part gets removed from the url 

The sorting seems to be after uid and did not get changed.

i use the orderby setting in the TS Setup provided by the Extension.

**Environment:**
- Typo3 11.5.16
- PHP 7.4
- pxa_product_manager 11.0.6

**Comment by bh-teufels** [comment]
if i add
`$this->addOrderings($queryBuilder, $demand);`
to the `createDemandQueryBuilder` inside the ProductRepoistory.php the sorting works

**Comment by MattiasNilsson** [comment]
@bh-teufels It works but you need to include TypoScript from the extension demander that is a dependency.

<img width="550" alt="Screenshot 2022-11-30 at 13 16 08" src="https://user-images.githubusercontent.com/1718315/204794804-8b3dee75-a43a-4c36-ba90-de6ca5a5dee6.png">
