### ISSUE TITLE
[BUG] translation of additionalAttributes for list not working

### ISSUE THREAD

**Issue by bh-teufels** [pixelant/pxa_product_manager#392]
**Describe the bug**
for the additonalAttrtibutes for list the translation is not working
The label are translated but the value is not 

**To Reproduce**

1. make translate  of attribute (Type 4: Dropdown) 
2. translate name, label, Options > value
3. add this attribute to plugin.tx_pxaproductmanager.settings.listView.additionalAttribute
4. output value of attribute selected option

**Expected behavior**
output value should be the translated not the default

**Environment**
- Typo3 11.5.19
- PHP 7.4

**Additional context**
may be problem only with vue.js output

**Comment by MattiasNilsson** [comment]
Thanks @bh-teufels for the report! We have acknowledge the error but I have a question. Do you use free mode or is it inherited language setup for TYPO3?

**Comment by bh-teufels** [comment]
i use connected mode (so inherited language setup)

**Comment by MattiasNilsson** [comment]
We have a new release that fixes this: https://github.com/pixelant/pxa_product_manager/releases/tag/v11.0.9
