### ISSUE TITLE
[BUG]: Attributes not working

### ISSUE THREAD

**Issue by arunspawoz** [pixelant/pxa_product_manager#403]
Hello,

I've recently included the latest version of the extension, and I found that the attributes values are not working. Also, the field label not showing. I've used an old version example 9.14.6 and it was working and the attributes fields are showing based on category selection. But in the latest version nothing is working and in frontend, the lazy loading view is also not showing. I want to display attributes in frontend for each product.

Please see the screenshot below.

Expecting a quick support for this issue.

Thank you.

![product-attributes-issue](https://user-images.githubusercontent.com/20816321/226833682-d4057e5b-cc7d-463a-894c-6a500719be45.png)

**Comment by MattiasNilsson** [comment]
Hi @arunspawoz you can find a similar issue here: https://github.com/pixelant/pxa_product_manager/issues/390
