### ISSUE TITLE
Link to External Manual on https://extensions.typo3.org/ does not work

### ISSUE THREAD

**Issue by Franzie** [pixelant/pxa_product_manager#95]
Clicking External Manual on https://extensions.typo3.org/extension/pxa_product_manager/
forwards to
https://www.typo3manual.com/extension-manuals/product-module/
which is a dead link. 404. Does not exist

**Comment by typo3ua** [comment]
You try is it ... http://www.typo3manual.com/extension-manuals/product-module/

**Comment by anjeylink** [comment]
ye, you should use http, but not httpS
